### ISSUE TITLE
No trace data

### ISSUE THREAD

**Issue by marzeck** [HerrMuellerluedenscheid/abedeto#3]
Hi there,

After solving the problem too small "_lmax_" I got a new problem. Somehow the abedeto process can't find the traces (so far tried and got error with GERES and BCA):
```
Traceback (most recent call last):
  File "/usr/local/bin/abedeto", line 665, in <module>
    process(args)
  File "/usr/local/bin/abedeto", line 338, in process
    plot(settings)
  File "/usr/local/lib/python2.7/dist-packages/abedeto/guesstimate_depth_v02.py", line 318, in plot
    tmax=onset+zoom_window[1]+correction)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/trace.py", line 526, in chop
    raise NoData()
pyrocko.trace.NoData
```
The traces were downloaded and even the beam was created and is visible with `abedeto snuffle`. 

Do you have an idea to solve that?
Thanks and cheers,
Marzeck

**Comment by marzeck** [comment]
I think this issue should be solved with the extended implementation of core phases. It ran into the problem to check for the wrong phases. Now it should work

**Comment by HerrMuellerluedenscheid** [comment]
Nice! Thanks for taking care of that
